export const ACTION_TYPE = {
	ADD_COMMENT: 'ADD_COMMENT',
	CLOSE_MODAL: 'CLOSE_MODAL',
	LOGOUT: 'LOGOUT',
	OPEN_MODAL: 'OPEN_MODAL',
	REMOVE_COMMENT: 'REMOVE_COMMENT',
	RESET_POST_DATA: 'RESET_POST_DATA',
	SET_POST_DATA: 'SET_POST_DATA',
	SET_USER: 'SET_USER',
};
